# Generated by Django 4.1.2 on 2022-10-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(max_length=255)),
                ('officeaddress', models.CharField(max_length=255)),
                ('officehead', models.CharField(max_length=255)),
                ('officeheadtnumber', models.CharField(max_length=255)),
            ],
        ),
    ]
