# Generated by Django 4.0.6 on 2022-11-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtssite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('view_customuser_info', 'Can view user info')]},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('view_news_new', 'Can view news')]},
        ),
        migrations.AlterModelOptions(
            name='productsinoffice',
            options={'permissions': [('view_products', 'Can view products in office')]},
        ),
    ]
