# Generated by Django 4.0.6 on 2022-11-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtssite', '0002_alter_customuser_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productsinoffice',
            options={},
        ),
    ]
