# Generated by Django 4.0.6 on 2022-10-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtssite', '0004_alter_news_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offices',
            new_name='Office',
        ),
    ]
